export const PARTIDO_LOGOS_FALLBACK = {
    "AVANTE": "https://commons.wikimedia.org/wiki/Special:FilePath/AVANTE_Brazil_Logo.png?width=250",
    "PT": "https://commons.wikimedia.org/wiki/Special:FilePath/PT_(Brazil)_logo_2021.svg?width=250",
    "MDB": "https://commons.wikimedia.org/wiki/Special:FilePath/Movimento_Democr%C3%A1tico_Brasileiro_(2017).svg?width=250",
    "PL": "https://commons.wikimedia.org/wiki/Special:FilePath/Partido_Liberal_(Brazil)_logo.svg?width=250",
    "PP": "https://commons.wikimedia.org/wiki/Special:FilePath/Progressistas_(Brazil)_logo.svg?width=250",
    "PODE": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Podemos_20.png?width=250",
    "PODEMOS": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Podemos_20.png?width=250",
    "PDT": "https://commons.wikimedia.org/wiki/Special:FilePath/LogoPDT.png?width=250",
    "PSB": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_the_Brazilian_Socialist_Party_(wordmark_color).svg?width=250",
    "PSD": "https://commons.wikimedia.org/wiki/Special:FilePath/PSD_Brazil_logo.svg?width=250",
    "PSDB": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_the_Brazilian_Social_Democracy_Party_(2023).svg?width=250",
    "UNIÃO": "https://commons.wikimedia.org/wiki/Special:FilePath/Uniao_Brasil.png?width=250",
    "UNIAO": "https://commons.wikimedia.org/wiki/Special:FilePath/Uniao_Brasil.png?width=250",
    "REPUBLICANOS": "https://commons.wikimedia.org/wiki/Special:FilePath/Republicanos_(Brazil)_logo.svg?width=250",
    "PSOL": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_PSOL_roxo.svg?width=250",
    "PCDOB": "https://commons.wikimedia.org/wiki/Special:FilePath/Pc_do_b_logo.svg?width=250",
    "PC DO B": "https://commons.wikimedia.org/wiki/Special:FilePath/Pc_do_b_logo.svg?width=250",
    "SOLIDARIEDADE": "https://commons.wikimedia.org/wiki/Special:FilePath/Solidariedade_(partido_pol%C3%ADtico)_logo.svg?width=250",
    "NOVO": "https://commons.wikimedia.org/wiki/Special:FilePath/NOVO_Logo_2023.png?width=250",
    "CIDADANIA": "https://commons.wikimedia.org/wiki/Special:FilePath/Cidadania_(partido_pol%C3%ADtico)_logo.svg?width=250",
    "PV": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Partido_Verde.svg?width=250",
    "REDE": "https://commons.wikimedia.org/wiki/Special:FilePath/Rede_Sustentabilidade_logo.svg?width=250",
    "PRD":     "https://commons.wikimedia.org/wiki/Special:FilePath/Partido_Renova%C3%A7%C3%A3o_Democr%C3%A1tica_logo.svg?width=250",
    "NOVA":    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Nova_Resist%C3%AAncia_logo.png/72px-Nova_Resist%C3%AAncia_logo.png",
    "MISSÃO":  "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Partido_Miss%C3%A3o.jpg",
    "MISSAO":  "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Partido_Miss%C3%A3o.jpg",
    "AGIR":    "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_do_Partido_Agir.png?width=250",
    "MOBILIZA":"https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_Partido_Mobiliza.png?width=250",
    "PSTU":    "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_PSTU.png?width=250",
    "PCB":     "https://commons.wikimedia.org/wiki/Special:FilePath/PCB_logo.svg?width=250",
    "PRTB":    "https://commons.wikimedia.org/wiki/Special:FilePath/Prtb.jpg?width=250",
    "PMB":     "https://commons.wikimedia.org/wiki/Special:FilePath/Pmb_logo_site-300x104.png?width=250",
    "PCO":     "https://commons.wikimedia.org/wiki/Special:FilePath/IMG3498Pco.png?width=250",
    "UP":      "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_-_UP_site.png?width=250",
};
