// Gerado automaticamente a partir de partido.csv e estados.csv
// Fonte única de verdade para logos de partidos e bandeiras de estados

export const PARTIDO_LOGOS_FALLBACK = {
  "UNIÃO":        "https://commons.wikimedia.org/wiki/Special:FilePath/Uni%C3%A3o_Brasil_logo.svg?width=250",
  "UNIAO":        "https://commons.wikimedia.org/wiki/Special:FilePath/Uni%C3%A3o_Brasil_logo.svg?width=250",
  "PP":           "https://commons.wikimedia.org/wiki/Special:FilePath/Progressistas_logotipo_%28cortado%29.png?width=250",
  "PV":           "https://commons.wikimedia.org/wiki/Special:FilePath/PV_Logo.svg?width=250",
  "PSB":          "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_the_Brazilian_Socialist_Party.svg?width=250",
  "PT":           "https://commons.wikimedia.org/wiki/Special:FilePath/PT_%28Brazil%29_logo_2021.svg?width=250",
  "REPUBLICANOS": "https://commons.wikimedia.org/wiki/Special:FilePath/Republicanos_10_logo.png?width=250",
  "PDT":          "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_do_Partido_Democr%C3%A1tico_Trabalhista%2C_do_Brasil.png?width=250",
  "PSOL":         "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_PSOL.png?width=250",
  "PL":           "https://commons.wikimedia.org/wiki/Special:FilePath/Partido_Liberal_(Brazil)_logo.svg?width=250",
  "MDB":          "https://commons.wikimedia.org/wiki/Special:FilePath/Movimento_Democr%C3%A1tico_Brasileiro_%282017%29.png?width=250",
  "PODE":         "https://commons.wikimedia.org/wiki/Special:FilePath/Logo-podemos.png?width=250",
  "PODEMOS":      "https://commons.wikimedia.org/wiki/Special:FilePath/Logo-podemos.png?width=250",
  "PCdoB":        "https://commons.wikimedia.org/wiki/Special:FilePath/PCdoB_%28comprimido%29.png?width=250",
  "PCDOB":        "https://commons.wikimedia.org/wiki/Special:FilePath/PCdoB_%28comprimido%29.png?width=250",
  "PC DO B":      "https://commons.wikimedia.org/wiki/Special:FilePath/PCdoB_%28comprimido%29.png?width=250",
  "PSD":          "https://commons.wikimedia.org/wiki/Special:FilePath/PSD_Brazil_logo.svg?width=250",
  "PSDB":         "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_the_Brazilian_Social_Democracy_Party_(2023).svg?width=250",
  "AVANTE":       "https://commons.wikimedia.org/wiki/Special:FilePath/AVANTE_Brazil_Logo.png?width=250",
  "CIDADANIA":    "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_Partido_Cidadania.png?width=250",
  "SOLIDARIEDADE":"https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_do_Partido_Solidariedade.png?width=250",
  "NOVO":         "https://commons.wikimedia.org/wiki/Special:FilePath/NOVO_Logo_2023.png?width=250",
  "REDE":         "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_da_Rede_Sustentabilidade_%28REDE%29%2C_do_Brasil_%28cropped%29.png?width=250",
  "PRD":          "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_Partido_Renova%C3%A7%C3%A3o_Democr%C3%A1tica.png?width=250",
  "MOBILIZA":     "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_Partido_Mobiliza.png?width=250",
  "AGIR":         "https://commons.wikimedia.org/wiki/Special:FilePath/Logomarca_do_Partido_Agir.png?width=250",
  "PRTB":         "https://commons.wikimedia.org/wiki/Special:FilePath/Prtb.jpg?width=250",
  "PSTU":         "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_PSTU.png?width=250",
  "PCB":          "https://commons.wikimedia.org/wiki/Special:FilePath/PCB_logo.svg?width=250",
  "MISSÃO":       "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Partido_Miss%C3%A3o.jpg?width=250",
};

export const ESTADO_LOGOS_FALLBACK = {
  "AC": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Acre.svg?width=250",
  "AL": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Alagoas.svg?width=250",
  "AM": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Amazonas.svg?width=250",
  "AP": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Amap%C3%A1.svg?width=250",
  "BA": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_da_Bahia.svg?width=250",
  "CE": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Cear%C3%A1.svg?width=250",
  "DF": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Distrito_Federal_%28Brasil%29.svg?width=250",
  "ES": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Esp%C3%ADrito_Santo.svg?width=250",
  "GO": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_Goi%C3%A1s.svg?width=250",
  "MA": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Maranh%C3%A3o.svg?width=250",
  "MG": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Minas_Gerais.svg?width=250",
  "MS": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Mato_Grosso_do_Sul.svg?width=250",
  "MT": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Mato_Grosso.svg?width=250",
  "PA": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Par%C3%A1.svg?width=250",
  "PB": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_da_Para%C3%ADba.svg?width=250",
  "PE": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Pernambuco.svg?width=250",
  "PI": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Piau%C3%AD.svg?width=250",
  "PR": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Paran%C3%A1.svg?width=250",
  "RJ": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_estado_do_Rio_de_Janeiro.svg?width=250",
  "RN": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Rio_Grande_do_Norte.svg?width=250",
  "RO": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Rond%C3%B4nia.svg?width=250",
  "RR": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Roraima.svg?width=250",
  "RS": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Rio_Grande_do_Sul.svg?width=250",
  "SC": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Santa_Catarina.svg?width=250",
  "SE": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Sergipe.svg?width=250",
  "SP": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_estado_de_S%C3%A3o_Paulo.svg?width=250",
  "TO": "https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Tocantins.svg?width=250",
};
